version: '3'
services:
    hi-nginx:
        build:
            context: ./app/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./app:/app
        depends_on:
            - hi-php-fpm
        ports:
            - "8080:80"
    hi-php-fpm:
        build:
            context: ./app/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./app:/app
        depends_on:
            - hi-postgres
    hi-php-cli:
        build:
            context: app/docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./app:/app
            - composer:/root/.composer/cache
        depends_on:
            - hi-postgres
        tty: true
    hi-postgres:
        image: postgres:13.2-alpine
        volumes:
            - hi-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"
    hi-nginx-admin:
        build:
            context: ./admin/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./admin:/admin
        depends_on:
            - hi-php-fpm
        ports:
            - "8081:80"
    hi-node:
        build:
            context: admin/docker/development
            dockerfile: node.docker
#        image: node:15.14-alpine
        volumes:
            - ./admin:/admin
#        working_dir: /admin
        ports:
            - "3001:3000"
        command: yarn start
        tty: true

    hi-node-cli:
        build:
            context: admin/docker/development
            dockerfile: node.docker
        volumes:
            - ./admin:/admin

volumes:
    hi-postgres:
    composer:
