version: '3'
services:
    api-nginx:
        build:
            context: api/docker/development/nginx
            dockerfile: Dockerfile
        volumes:
            - ./api:/api
        depends_on:
            - api-php-fpm
        ports:
            - "8080:80"
    api-php-fpm:
        build:
            context: api/docker/development
            dockerfile: php-fpm/Dockerfile
        volumes:
            - ./api:/api
        depends_on:
            - api-postgres
    api-php-cli:
        build:
            context: api/docker/development
            dockerfile: php-cli/Dockerfile
        volumes:
            - ./api:/api
            - composer:/root/.composer/cache
        depends_on:
            - api-postgres
        tty: true
    api-postgres:
        image: postgres:14.1-alpine
        volumes:
            - api-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: hawaii
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: hawaii
        ports:
            - "54321:5432"
    frontend-node:
        build:
            context: frontend/docker/development/node
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/frontend
        ports:
            - "3001:3000"
        tty: true

volumes:
    api-postgres:
    composer:
