doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: UTF8
        server_version: 14.1
        types:
            entity_id: App\Infrastructure\Domain\Model\DoctrineEntityIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            EAV:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/EAV/Entity'
                prefix: 'App\Domain\EAV\Entity'
                alias: EAV
